# Generated by Django 5.1.6 on 2025-03-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeProfile',
            fields=[
                ('trainee_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainee_first_name', models.CharField(max_length=100)),
                ('trainee_last_name', models.CharField(max_length=100)),
                ('trainee_email', models.EmailField(max_length=254)),
                ('trainee_phone', models.IntegerField()),
                ('trainee_address', models.CharField(max_length=100)),
                ('trainee_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
