# Generated by Django 5.1.6 on 2025-03-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeprofile',
            name='trainee_status',
            field=models.BooleanField(default=True),
        ),
    ]
