# Generated by Django 5.1.6 on 2025-03-17 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_alter_tracks_track_id'),
        ('trainee', '0003_remove_traineeprofile_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeprofile',
            name='track_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='track.tracks'),
        ),
    ]
