# Generated by Django 5.1.6 on 2025-03-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_duration', models.CharField(max_length=100)),
                ('course_fee', models.CharField(max_length=100)),
                ('course_trainer', models.CharField(max_length=100)),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
            ],
        ),
    ]
