# Generated by Django 5.1.6 on 2025-03-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_track',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
