# Generated by Django 5.1.6 on 2025-03-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_courses_track_id'),
        ('track', '0006_alter_tracks_track_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='track_id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='track.tracks'),
        ),
    ]
