# Generated by Django 5.1.6 on 2025-03-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('track_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=50, null=True)),
                ('track_duration', models.CharField(max_length=50, null=True)),
                ('track_supervisor', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
