# Generated by Django 5.1.6 on 2025-03-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_tracks_track_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='track_date',
            new_name='track_end_date',
        ),
        migrations.AddField(
            model_name='tracks',
            name='track_start_date',
            field=models.DateField(null=True),
        ),
    ]
