# Generated by Django 5.1.6 on 2025-03-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_rename_track_date_tracks_track_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='track_status',
            field=models.BooleanField(default=True),
        ),
    ]
