# Generated by Django 5.1.6 on 2025-03-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_tracks_track_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
