# Generated by Django 5.1.6 on 2025-03-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_alter_tracks_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='track_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
